convert_to_aa: true
eval_steps: 100
evaluation_strategy: steps
fp16: false
gradient_accumulation_steps: 2
learning_rate: 5.0e-05
load_best_model_at_end: true
logging_steps: 500
logging_strategy: steps
num_char_per_token: 1
num_train_epochs: 50
output_dir: bpe_llm_out
per_device_eval_batch_size: 64
per_device_train_batch_size: 32
save_steps: 100
save_total_limit: 5
tokenizer_path: tokenizers/saved_tokenizers/ape_tokenizer
train_path: /home/couchbucks/Downloads/all_fasta_files/training/GCA_000977415.2_Sc_YJM1385_v1_genomic_extracted_sequences.fasta
validation_path: /home/couchbucks/Downloads/all_fasta_files/training/GCA_000977415.2_Sc_YJM1385_v1_genomic_extracted_sequences.fasta
wandb_project: ''
warmup_steps: 1000
weight_decay: 0.01
